manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/hanjin-kim
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: config/west.yml
  self:
    path: config
